# Dependencies
markdown:         kramdown #redcarpet
highlighter:      Rouge #pygments

# Permalinks
permalink:        pretty
# relative_permalinks: true

# Setup
title:            Fathur Rohmann
tagline:          'A Jekyll theme'
description:      'A brazen two-column <a href="http://jekyllrb.com" target="_blank">Jekyll</a> theme that pairs a prominent sidebar with uncomplicated content. Made by <a href="https://twitter.com/mdo" target="_blank">@mdo</a>.'
url:              https://fathur.github.io
baseurl:          /

author:
  name:           'Fathur Rohman'
  url:            https://twitter.com/__rohman__

paginate:         5

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/fathur/fathur.github.io

plugins:
  - jekyll-paginate
